apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-api-gateway-service
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: bookstore-api-gateway-service
        image: rajureddy98/bookstore-api-gateway-service:2.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8765
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway-service
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8765
