- hosts: all
  strategy: free
  tasks:
  - name: update all packages
    become: yes
    ignore_errors: yes
    yum:
      name: "*"
      state: latest
    register: upout
    tags: upout
-  hosts: all
   strategy: free
   tasks:
   - name: install containerd runtime for kubernetes
     become: yes
     shell: |
       yum install yum-utils -y
       yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
       yum install containerd.io -y
       CONTAINDERD_CONFIG_PATH=/etc/containerd/config.toml && \
       rm "${CONTAINDERD_CONFIG_PATH}" && \
       containerd config default > "${CONTAINDERD_CONFIG_PATH}" && \
       sed -i "s/SystemdCgroup = false/SystemdCgroup = true/g"  "${CONTAINDERD_CONFIG_PATH}"
       systemctl enable --now containerd && \
       systemctl restart containerd
-  hosts: all
   tasks:
   - name: add kubernetes repositiry
     become: yes
     shell: |
         cat <<EOF > /etc/yum.repos.d/kubernetes.repo
         [kubernetes]
         name=Kubernetes
         baseurl=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
         enabled=1
         gpgcheck=1
         gpgkey=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
         exclude=kubelet kubeadm kubectl
         EOF
     register: lsout
     tags: lsout

- hosts: all
  strategy: free
  tasks:
  - name: installing kubernetes components
    become: yes
    yum:
      name:
        - kubelet
        - kubeadm
        - kubectl
      state: latest
    delay: 200
  - name: enable kubelet
    become: yes
    service:
      name: kubelet
      enabled: true
      state: started

  - name: update ip tables
    become: yes
    shell: |
      modprobe br_netfilter
      cat <<EOF > /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      EOF
      sysctl --system

  - name: disable SELinux and swap memory and firewall
    become: yes
    shell: |
      sudo setenforce 0
      sudo sed -i ‘s/^SELINUX=enforcing$/SELINUX=permissive/’ /etc/selinux/config
      sudo sed -i '/swap/d' /etc/fstab
      sudo swapoff -a
      systemctl stop firewalld
      systemctl disable firewalld
      echo 1 > /proc/sys/net/ipv4/ip_forward
      kubeadm reset --force

- hosts: master-node
  become: true
  tasks:
  - name: initiate the cluster
    shell: |
      sudo kubeadm init --pod-network-cidr=10.244.0.0/16
    register: ps
  - debug: var=ps.stdout_lines

- hosts: master-node
  become: true
  tasks:
  - name: setup kube-config, pod-network
    shell: |
      mkdir -p $HOME/.kube
      sudo yes | cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config
      kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

  - name: print kubeadm join command
    command: kubeadm token create --print-join-command
    register: kubernetes_join_command

  - name: Copy join command to local file.
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

- hosts: worker-nodes
  become: true
  tasks:
    - name: Copy join command from Ansiblehost to the worker nodes
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Join the Worker nodes to the cluster.
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not
