apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-account-service
  labels: 
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: bookstore-account-service
        image: rajureddy98/bookstore-account-service:2.0
        ports:
          - containerPort: 4001
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTIONS
          value: "-Dspring.profiles.active=local"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  type: ClusterIP
  selector:
    app: account
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001
