apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-order-service
  labels: 
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: bookstore-order-service
        image: rajureddy98/bookstore-order-service:2.0
        ports:
          - containerPort: 7001
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTIONS
          value: "-Dspring.profiles.active=local"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
  - protocol: TCP
    port: 7001
    targetPort: 7001
