name: Pass a parameter into a custom action
description: Receives a parameter and prints it out.

inputs:
  custom_param:
    description: Custom input parameter
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      name: Print the parameter value
      env:
        custom_param: ${{ inputs.custom_param }}
      run: |
        echo 'About to echo the parameter value'
        echo "$custom_param"
