name: my workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set FOO
      run: echo "FOO=${{ github.event.inputs.foo }}" >> $GITHUB_ENV
    - name: Test
      run: echo $FOO
